---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jitsi
  namespace: jitsi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: jitsi
  name: jitsi
  namespace: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: jitsi
  template:
    metadata:
      labels:
        k8s-app: jitsi
    spec:
      containers:
        - name: jicofo
          image: jitsi/jicofo:stable-6826
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: '{{ BITBUCKET_REPO_SLUG }}-kustomize-secret'
        - name: prosody
          image: jitsi/prosody:stable-6826
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: '{{ BITBUCKET_REPO_SLUG }}-kustomize-secret'
        - name: web
          image: jitsi/web:stable-6826
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: '{{ BITBUCKET_REPO_SLUG }}-kustomize-secret'
        - name: jvb
          image: jitsi/jvb:stable-6826
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: '{{ BITBUCKET_REPO_SLUG }}-kustomize-secret'
      serviceAccountName: jitsi